import { useMemo, useState } from "react";
import Link from "next/link";
import Scanner from "../components/Scanner";

function parsePayload(payload) {
  if (!payload) return null;

  if (payload.includes("~")) {
    const parts = payload.split("~");
    if (parts.length !== 4) return null;

    const rawDate = parts[2] || "";
    const normalizedDate =
      rawDate.length === 8
        ? `${rawDate.slice(0, 4)}-${rawDate.slice(4, 6)}-${rawDate.slice(6, 8)}`
        : rawDate;

    return {
      modelNo: decodeURIComponent(parts[0] || "") || "-",
      sequenceNumber: decodeURIComponent(parts[1] || "") || "-",
      installationDate: normalizedDate || "-",
      location: decodeURIComponent(parts[3] || "") || "-",
    };
  }

  const parts = payload.split(";");
  const mapped = {};

  for (const part of parts) {
    const [key, ...rest] = part.split("=");
    if (!key || rest.length === 0) continue;
    mapped[key] = decodeURIComponent(rest.join("="));
  }

  if (!mapped.MODEL && !mapped.SEQ && !mapped.DATE && !mapped.LOC) {
    return null;
  }

  return {
    modelNo: mapped.MODEL || "-",
    sequenceNumber: mapped.SEQ || "-",
    installationDate: mapped.DATE || "-",
    location: mapped.LOC || "-",
  };
}

export default function ScanPage() {
  const [decodedValue, setDecodedValue] = useState("");
  const details = useMemo(() => parsePayload(decodedValue), [decodedValue]);

  return (
    <main className="page-shell">
      <header className="page-header">
        <Link href="/" className="text-link">
          Back
        </Link>
        <h1>Scan Barcode</h1>
      </header>

      <Scanner onDecode={setDecodedValue} />

      <section className="panel">
        <h2>Decoded Output</h2>
        {!decodedValue && (
          <p className="muted">
            Start camera scanning or upload an image to decode a barcode.
          </p>
        )}

        {decodedValue && (
          <>
            <p className="raw-output">{decodedValue}</p>
            {details ? (
              <div className="details-grid">
                <div>
                  <strong>Model No.</strong>
                  <p>{details.modelNo}</p>
                </div>
                <div>
                  <strong>Sequence Number</strong>
                  <p>{details.sequenceNumber}</p>
                </div>
                <div>
                  <strong>Date of Installation</strong>
                  <p>{details.installationDate}</p>
                </div>
                <div>
                  <strong>Location</strong>
                  <p>{details.location}</p>
                </div>
              </div>
            ) : (
              <p className="muted">
                This barcode does not match the expected format generated by
                this app.
              </p>
            )}
          </>
        )}
      </section>
    </main>
  );
}
